name: Build Docker image

on:
  release:
    types: [published]
  pull_request:
    branches:
      - develop
      - master
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build_docker_image:
    name: Build Docker image (PR)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file ./src/StackFood.Lambda/Dockerfile --tag my-image-name:$(date +%s)